<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $students = [
            // X Merdeka 1
            [
                'nis' => '242510001',
                'nisn' => '0081234001',
                'name' => 'ADITYA PRATAMA',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2008-04-12',
                'religion' => 'Islam',
                'address' => 'Jl. Pembangunan No. 12, Tarogong Kidul, Garut',
                'phone' => '081234567001',
                'previous_school' => 'SMPN 1 Garut',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2024-07-15',
                'father_name' => 'Bambang Pratama',
                'mother_name' => 'Sri Wahyuni',
                'father_occupation' => 'Wiraswasta',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765001',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 1',
            ],
            [
                'nis' => '242510002',
                'nisn' => '0081234002',
                'name' => 'ANISA RAHMAWATI',
                'gender' => 'P',
                'birth_place' => 'Bandung',
                'birth_date' => '2008-07-23',
                'religion' => 'Islam',
                'address' => 'Jl. Cimanuk No. 45, Garut Kota',
                'phone' => '081234567002',
                'previous_school' => 'SMPN 2 Garut',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2024-07-15',
                'father_name' => 'Ahmad Rahmanto',
                'mother_name' => 'Dewi Lestari',
                'father_occupation' => 'PNS',
                'mother_occupation' => 'Guru',
                'parent_phone' => '081298765002',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 1',
            ],
            [
                'nis' => '242510003',
                'nisn' => '0081234003',
                'name' => 'BAYU SETIAWAN',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2008-01-18',
                'religion' => 'Islam',
                'address' => 'Kp. Sukadana RT 02/05, Tarogong Kaler, Garut',
                'phone' => '081234567003',
                'previous_school' => 'SMPN 1 Tarogong Kaler',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2024-07-15',
                'father_name' => 'Cecep Setiawan',
                'mother_name' => 'Eni Rohaeni',
                'father_occupation' => 'Petani',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765003',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 1',
            ],

            // X Merdeka 2
            [
                'nis' => '242510004',
                'nisn' => '0081234004',
                'name' => 'CITRA DEWI LESTARI',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2008-09-05',
                'religion' => 'Islam',
                'address' => 'Jl. Terusan Pahlawan No. 8, Garut Kota',
                'phone' => '081234567004',
                'previous_school' => 'SMPN 3 Garut',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2024-07-15',
                'father_name' => 'Deden Kurnia',
                'mother_name' => 'Rina Marlina',
                'father_occupation' => 'Karyawan Swasta',
                'mother_occupation' => 'Wiraswasta',
                'parent_phone' => '081298765004',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 2',
            ],
            [
                'nis' => '242510005',
                'nisn' => '0081234005',
                'name' => 'DIMAS ARYA PUTRA',
                'gender' => 'L',
                'birth_place' => 'Tasikmalaya',
                'birth_date' => '2008-03-30',
                'religion' => 'Islam',
                'address' => 'Perum Permata Indah Blok B3, Tarogong Kidul',
                'phone' => '081234567005',
                'previous_school' => 'SMP Plus Al-Hikmah',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2024-07-15',
                'father_name' => 'Endang Sudrajat',
                'mother_name' => 'Nurjanah',
                'father_occupation' => 'PNS',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765005',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 2',
            ],
            [
                'nis' => '242510006',
                'nisn' => '0081234006',
                'name' => 'DWI INDAH PERMATA',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2008-11-14',
                'religion' => 'Islam',
                'address' => 'Jl. Papandayan No. 21, Garut Kota',
                'phone' => '081234567006',
                'previous_school' => 'SMPN 1 Garut',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2024-07-15',
                'father_name' => 'Farid Hidayat',
                'mother_name' => 'Tuti Alawiyah',
                'father_occupation' => 'Pedagang',
                'mother_occupation' => 'Pedagang',
                'parent_phone' => '081298765006',
                'status' => 'Aktif',
                'current_class_name' => 'X Merdeka 2',
            ],

            // XI F1
            [
                'nis' => '232410007',
                'nisn' => '0071234007',
                'name' => 'FAJAR NUGRAHA',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2007-06-20',
                'religion' => 'Islam',
                'address' => 'Jl. Patriot No. 19, Garut',
                'phone' => '081234567007',
                'previous_school' => 'SMPN 4 Garut',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2023-07-17',
                'father_name' => 'Gunawan Nugraha',
                'mother_name' => 'Yayah Rokayah',
                'father_occupation' => 'TNI',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765007',
                'status' => 'Aktif',
                'current_class_name' => 'XI F1',
            ],
            [
                'nis' => '232410008',
                'nisn' => '0071234008',
                'name' => 'GITA SAVITRI',
                'gender' => 'P',
                'birth_place' => 'Jakarta',
                'birth_date' => '2007-08-11',
                'religion' => 'Islam',
                'address' => 'Jl. Bratayuda No. 77, Garut Kota',
                'phone' => '081234567008',
                'previous_school' => 'SMPN 1 Garut',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2023-07-17',
                'father_name' => 'Hasanudin',
                'mother_name' => 'Ratna Juwita',
                'father_occupation' => 'BUMN',
                'mother_occupation' => 'PNS',
                'parent_phone' => '081298765008',
                'status' => 'Aktif',
                'current_class_name' => 'XI F1',
            ],
            [
                'nis' => '232410009',
                'nisn' => '0071234009',
                'name' => 'HENDRA WIJAYA',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2007-10-02',
                'religion' => 'Islam',
                'address' => 'Kp. Babakan Abid No. 5, Tarogong Kidul',
                'phone' => '081234567009',
                'previous_school' => 'SMPN 2 Tarogong Kidul',
                'accepted_class' => 'X Merdeka 3',
                'admission_date' => '2023-07-17',
                'father_name' => 'Iwan Wijaya',
                'mother_name' => 'Kokom Komariah',
                'father_occupation' => 'Buruh Harian Lepas',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765009',
                'status' => 'Aktif',
                'current_class_name' => 'XI F1',
            ],

            // XI F2
            [
                'nis' => '232410010',
                'nisn' => '0071234010',
                'name' => 'INTAN NUR AINI',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2007-02-15',
                'religion' => 'Islam',
                'address' => 'Jl. Samarang No. 102, Garut',
                'phone' => '081234567010',
                'previous_school' => 'SMP IT Baitul Hikmah',
                'accepted_class' => 'X Merdeka 4',
                'admission_date' => '2023-07-17',
                'father_name' => 'Jajang Sulaeman',
                'mother_name' => 'Ai Nurhayati',
                'father_occupation' => 'Wiraswasta',
                'mother_occupation' => 'Wiraswasta',
                'parent_phone' => '081298765010',
                'status' => 'Aktif',
                'current_class_name' => 'XI F2',
            ],
            [
                'nis' => '232410011',
                'nisn' => '0071234011',
                'name' => 'JOKO PRASETYO',
                'gender' => 'L',
                'birth_place' => 'Solo',
                'birth_date' => '2007-05-09',
                'religion' => 'Islam',
                'address' => 'Asrama Korem Tarogong, Garut',
                'phone' => '081234567011',
                'previous_school' => 'SMP Kartika Bandung',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2023-07-17',
                'father_name' => 'Kusworo Prasetyo',
                'mother_name' => 'Tri Hastuti',
                'father_occupation' => 'TNI',
                'mother_occupation' => 'PNS',
                'parent_phone' => '081298765011',
                'status' => 'Aktif',
                'current_class_name' => 'XI F2',
            ],
            [
                'nis' => '232410012',
                'nisn' => '0071234012',
                'name' => 'KARTIKA SARI',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2007-12-28',
                'religion' => 'Islam',
                'address' => 'Jl. Merdeka No. 34, Tarogong Kidul',
                'phone' => '081234567012',
                'previous_school' => 'SMPN 1 Garut',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2023-07-17',
                'father_name' => 'Lukman Hakim',
                'mother_name' => 'Siti Khodijah',
                'father_occupation' => 'Pensiunan',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765012',
                'status' => 'Aktif',
                'current_class_name' => 'XI F2',
            ],

            // XII MIPA 1
            [
                'nis' => '222310013',
                'nisn' => '0061234013',
                'name' => 'LUKMAN MAULANA',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2006-05-14',
                'religion' => 'Islam',
                'address' => 'Kp. Sindang Reret No. 17, Tarogong Kaler',
                'phone' => '081234567013',
                'previous_school' => 'SMPN 1 Tarogong Kaler',
                'accepted_class' => 'X MIPA 1',
                'admission_date' => '2022-07-18',
                'father_name' => 'Maman Sulaeman',
                'mother_name' => 'Neneng Hasanah',
                'father_occupation' => 'Wiraswasta',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765013',
                'status' => 'Aktif',
                'current_class_name' => 'XII MIPA 1',
            ],
            [
                'nis' => '222310014',
                'nisn' => '0061234014',
                'name' => 'MAYA ANGGRAENI',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2006-09-19',
                'religion' => 'Islam',
                'address' => 'Jl. Bank No. 9, Garut Kota',
                'phone' => '081234567014',
                'previous_school' => 'SMPN 2 Garut',
                'accepted_class' => 'X MIPA 1',
                'admission_date' => '2022-07-18',
                'father_name' => 'Nana Suryana',
                'mother_name' => 'Euis Rohayati',
                'father_occupation' => 'PNS',
                'mother_occupation' => 'Bidan',
                'parent_phone' => '081298765014',
                'status' => 'Aktif',
                'current_class_name' => 'XII MIPA 1',
            ],

            // XII IPS 1
            [
                'nis' => '222310015',
                'nisn' => '0061234015',
                'name' => 'NAUFAL FADHLURRAHMAN',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2006-03-08',
                'religion' => 'Islam',
                'address' => 'Jl. Raya Bayongbong Km 4, Garut',
                'phone' => '081234567015',
                'previous_school' => 'SMPN 1 Bayongbong',
                'accepted_class' => 'X IPS 1',
                'admission_date' => '2022-07-18',
                'father_name' => 'Oman Komarudin',
                'mother_name' => 'Lilis Suryani',
                'father_occupation' => 'Pengusaha',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765015',
                'status' => 'Aktif',
                'current_class_name' => 'XII IPS 1',
            ],
            [
                'nis' => '222310016',
                'nisn' => '0061234016',
                'name' => 'PUTRI AYU NINGSIH',
                'gender' => 'P',
                'birth_place' => 'Ciamis',
                'birth_date' => '2006-11-22',
                'religion' => 'Islam',
                'address' => 'Jl. Pasundan No. 51, Garut Kota',
                'phone' => '081234567016',
                'previous_school' => 'SMPN 3 Ciamis',
                'accepted_class' => 'X IPS 1',
                'admission_date' => '2022-07-18',
                'father_name' => 'Purnomo',
                'mother_name' => 'Sumarni',
                'father_occupation' => 'Karyawan Swasta',
                'mother_occupation' => 'Penjahit',
                'parent_phone' => '081298765016',
                'status' => 'Aktif',
                'current_class_name' => 'XII IPS 1',
            ],

            // Alumni (2 records for testing filter & summary cards)
            [
                'nis' => '212210017',
                'nisn' => '0051234017',
                'name' => 'RAHMAD HIDAYATULLAH',
                'gender' => 'L',
                'birth_place' => 'Garut',
                'birth_date' => '2005-04-05',
                'religion' => 'Islam',
                'address' => 'Kp. Bojong Larang No. 11, Garut Kota',
                'phone' => '081234567017',
                'previous_school' => 'SMPN 1 Garut',
                'accepted_class' => 'X MIPA 1',
                'admission_date' => '2021-07-12',
                'father_name' => 'Ridwan Hidayat',
                'mother_name' => 'Nur Aisyah',
                'father_occupation' => 'PNS',
                'mother_occupation' => 'PNS',
                'parent_phone' => '081298765017',
                'status' => 'Alumni',
                'current_class_name' => 'XII MIPA 1',
            ],
            [
                'nis' => '212210018',
                'nisn' => '0051234018',
                'name' => 'RINA WIDYASTUTI',
                'gender' => 'P',
                'birth_place' => 'Garut',
                'birth_date' => '2005-08-30',
                'religion' => 'Islam',
                'address' => 'Jl. Guntur Indah No. 2, Tarogong Kidul',
                'phone' => '081234567018',
                'previous_school' => 'SMPN 2 Garut',
                'accepted_class' => 'X IPS 2',
                'admission_date' => '2021-07-12',
                'father_name' => 'Sukirman',
                'mother_name' => 'Yanti Maryanti',
                'father_occupation' => 'Wiraswasta',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765018',
                'status' => 'Alumni',
                'current_class_name' => 'XII IPS 2',
            ],

            // Mutasi (2 records for testing filter & summary cards)
            [
                'nis' => '242510019',
                'nisn' => '0081234019',
                'name' => 'SURYA DHARMA',
                'gender' => 'L',
                'birth_place' => 'Medan',
                'birth_date' => '2008-10-10',
                'religion' => 'Islam',
                'address' => 'Jl. Otista No. 88, Tarogong Kaler',
                'phone' => '081234567019',
                'previous_school' => 'SMP Harapan 1 Medan',
                'accepted_class' => 'X Merdeka 1',
                'admission_date' => '2024-07-15',
                'father_name' => 'Tigor Siregar',
                'mother_name' => 'Nurhalimah',
                'father_occupation' => 'Polri',
                'mother_occupation' => 'Ibu Rumah Tangga',
                'parent_phone' => '081298765019',
                'status' => 'Mutasi',
                'current_class_name' => 'X Merdeka 1',
            ],
            [
                'nis' => '232410020',
                'nisn' => '0071234020',
                'name' => 'TIARA ANDINI',
                'gender' => 'P',
                'birth_place' => 'Jember',
                'birth_date' => '2007-09-23',
                'religion' => 'Islam',
                'address' => 'Jl. Raya Samarang No. 55, Garut',
                'phone' => '081234567020',
                'previous_school' => 'SMPN 1 Jember',
                'accepted_class' => 'X Merdeka 2',
                'admission_date' => '2023-07-17',
                'father_name' => 'Wahyu Nugroho',
                'mother_name' => 'Sari Indah',
                'father_occupation' => 'Dosen',
                'mother_occupation' => 'PNS',
                'parent_phone' => '081298765020',
                'status' => 'Mutasi',
                'current_class_name' => 'XI F2',
            ],
        ];

        foreach ($students as $studentData) {
            // Re-run safe: only insert if NIS does not exist yet
            Student::firstOrCreate(
                ['nis' => $studentData['nis']],
                $studentData
            );
        }
    }
}
